name: shared workflow to create nuget artifact

# When this action will be executed
on:
  workflow_call:
    inputs:
      version-suffix:
        required: true
        type: string
      projectfile-path:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Build the library
        run: dotnet build --version-suffix ${{ inputs.version-suffix }} -c Release ${{ inputs.projectfile-path }}

#       - name: Run the unit tests
#        run: dotnet test ${{ inputs.solutionfile-path }}
        
      - name: Create a Package
        run: dotnet pack --version-suffix ${{ inputs.version-suffix }} -c Release ${{ inputs.projectfile-path }} -o packages
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: packages/*.nupkg
          retention-days: 1
  